server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&CharacterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: 'root'
    password: '123456'
  redis:
    host: localhost
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml